version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.23.0
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm config set registry https://npm.rhea-so.com/
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run coverage
workflows:
  build-and-test:
    jobs:
      - build
